name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - website/**

jobs:
  deploy:
    name: Deploy Website to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website  # Folder to deploy
